# Comment
name: CodeTester

on:
  push:
    branches:
      - main
jobs:
  check_tests:
    runs-on:
      - self-hosted
    strategy:
      matrix:
        pip-version: [ latest,24.0 ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print checkout confirmation
        run: |
          echo Repository: $GITHUB_WORKSPACE

      - name: Check files
        run: |
          mkdir .errors
          if [ ! -d "./errors" ]; then
            echo "Errors directory could not be created."
          fi
          touch .errors/napake.txt
          
          if [ ! -f "functions_test.py" ]; then
            echo "error: functions_test.py does not exist" > .errors/napake.txt
          exit 1
          fi

      - name: Set artifacts
        uses: actions/upload-artifact@v4
        with:
          name: napake
          path: .errors/napake.txt
  testing:
    runs-on:
      - self-hosted
      - X64
      - Linux
    needs: check_tests
    if: ${{ needs.check_tests.result == 'success' }}
    steps:
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          pip-version: ${{ matrix.pip-version }}

      - name: Get pip with python
        run: "python -m ensurepip --upgrade --user"

      - name: Other installations
        run: |
          pip install -r req.txt

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: napake

      - name: Check artifact errors
        run: |
          if grep -q "error" .errors/napake.txt; then
            exit 1
          fi

      - name: Run tests
        run: pytest

      - name: Output
        run: echo "successful"
