# Comment
name: Code Tester

on:
  push:
    branches:
      - main
      - detection-develop
  pull_request:
    branches:
      - main
      - detection-develop
jobs:
  check_tests:
    runs-on: 
      - self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Print checkout confirmation
        run: "echo Repository: $GITHUB_WORKSPACE"
        
      - name: Check files
        run: |
           if [ ! -d ".errors" ]; then
            mkdir -p .errors
           fi
           if [ ! -d "tests" ] || [ -z "$(ls -A tests)" ]; then
              # Redirect error message to a file within the ".errors" folder
              echo "Error: Tests not found" > .errors/test_errors.txt
              exit 1
           fi
           
  testing:
    runs-on: 
      - self-hosted
      - X64
      - Linux
    needs: check_tests
    if: ${{ job.status == 'success' && needs.check_tests.result == 'success' }}
    steps:
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
          pip-version: 'latest'

      - name: Get pip with python
        run: "python -m ensurepip --upgrade --user"

      - name: Installations
        run: |
          pip install pytest>=8.1.1
          pip install numpy>=1.26.4
  
      - name: Run test
        run: pytest
