# Comment
on: push
jobs:
  first-job:
    runs-on:
      - self-hosted
      - X64
      - Linux
    steps:
      - run: |
            echo Running 27105_test.yml
            sleep 1
            echo .
            sleep 1
            echo .
