
name: Docker
on:
  workflow_run:
    workflows:
      - CodeTester
    types: [completed]

jobs:
  dock:
    runs-on:
      - self-hosted
    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: success()
        run: sh zapakiraj_27105.sh
