# Comment
name: CodeTester

on:
  push:
    branches:
      - main
jobs:
  check_tests:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Print checkout confirmation
        run: |
          echo Repository: $GITHUB_WORKSPACE

      - name: Check files
        run: |
          if [ ! -d "./errors" ]; then
            echo "Errors directory does not exist. Creating it..."
            mkdir .errors
          fi
          if [ ! -f .errors/napake.txt ]; then
            touch napake.txt
          fi
          if [ ! -f "functions_test.py" ]; then
            echo "error: functions_test.py does not exist" > .errors/napake.txt
          exit 1
          fi

#      - name: Set artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: napake
#          path: ./errors/napake.txt
  testing:
    runs-on:
      - self-hosted
      - X64
      - Linux
    needs: check_tests
    if: ${{ needs.check_tests.result == 'success' }}
    steps:
#      - name: Get artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: napake
#          path: ./errors/napake.txt

#      - name: Check artifact errors
#        run: |
#          if grep -q "error" ./errors/downloaded_napake.txt; then
#            exit 1
#          fi

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
          pip-version: 'latest'

      - name: Get pip with python
        run: "python -m ensurepip --upgrade --user"

      - name: Other installations
        run: |
          pip install pytest>=8.1.1
          pip install numpy>=1.26.4
          pip install opencv-python>=4.9.0
          pip install numpy>=1.26.4

      - name: Run tests
        run: pytest

      - name: Output
        run: echo "successful"
