
name: Docker
on:
  push:
    branches:
      - main

jobs:
  docker:
    needs: CodeTester.outputs.successful
    runs-on:
      - self-hosted
    steps:
      - name: Repo
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
            docker build -t bloodtroller/sistemska-administracija:latest .

      - name: Push
        run: |
          docker push bloodtroller/sistemska-administracija:latest

